name: Git Auto Commit

on: 
  pull_request:
  push:
      branches:
        - main

jobs:
  format-code:
    runs-on: windows-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.head_ref}}

      # Other steps that change files in the repository

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
         commit_message: Update Network Visualisation
 	